version: "3.1"

services:
  db:
    image: postgres:latest
    container_name: pg-db
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=movie_list
  api:
    image: express-docker
    container_name: backend
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "8080:8080"
    environment:
      - DB_CONNECTION_STRING=postgres://postgres:docker@db/movie_list
    networks:
      - app_network
    depends_on:
      - db
  ui:
    image: react-docker
    container_name: frontend
    build: ./movie-list
    volumes:
      - ./movie-list:/app
    ports:
      - "3000:3000"
    networks:
      - app_network
    depends_on:
      - api

networks:
  app_network:
    driver: bridge