/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('movies').del()
  await knex("movies").insert([
    {
      title: "The Dark Knight",
      genre: "Drama",
      synopsis: `When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.`,
      release_date: "2008",
      rating: "PG-13",
      runtime: "2h 32m",
      director: "Christopher Nolan",
      poster_url:
        "https://m.media-amazon.com/images/I/818hyvdVfvL._AC_SL1500_.jpg",
      imdb_score: "9.0",
      user_score: "",
      user_review: "",
      watch: false,
      to_watch: false,
    },
    {
      title: "The Big Lebowski",
      genre: "Comedy",
      synopsis: `Jeff "The Dude" Lebowski, mistaken for a millionaire of the same name, seeks restitution for his ruined rug and enlists his bowling buddies to help get it.`,
      release_date: "1998",
      rating: "R",
      runtime: "1h 57m",
      director: "Joel & Ethan Coen",
      poster_url:
        "https://m.media-amazon.com/images/I/71in2PwN26L._AC_SL1000_.jpg",
      imdb_score: "8.1",
      user_score: "",
      user_review: "",
      watch: false,
      to_watch: false,
    },
    {
      title: "Aliens",
      genre: "Sci-Fi",
      synopsis: `Decades after surviving the Nostromo incident, Ellen Ripley is sent out to re-establish contact with a terraforming colony but finds herself battling the Alien Queen and her offspring.`,
      release_date: "1986",
      rating: "R",
      runtime: "2h 17m",
      director: "James Cameron",
      poster_url:
        "https://m.media-amazon.com/images/I/614Po7VWOEL._AC_SL1500_.jpg",
      imdb_score: "8.4",
      user_score: "",
      user_review: "",
      watch: false,
      to_watch: false,
    },
    {
      title: "Avengers: Infinity War",
      genre: "Action",
      synopsis: `The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.`,
      release_date: "2018",
      rating: "PG-13",
      runtime: "2h 29m",
      director: "Anthony & Joe Russo",
      poster_url:
        "https://m.media-amazon.com/images/I/71eHZFw+GlL._AC_SL1000_.jpg",
      imdb_score: "8.4",
      user_score: "",
      user_review: "",
      watch: false,
      to_watch: false,
    },
    {
      title: "Spiderman: Accross the Spider-Verse",
      genre: "Action",
      synopsis: `Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. When the heroes clash on how to handle a new threat, Miles must redefine what it means to be a hero.`,
      release_date: "2023",
      rating: "PG",
      runtime: "2h 20m",
      director: "Joaquim Dos Santos, Kemp Powers, Justin K. Thompson",
      poster_url:
        "https://m.media-amazon.com/images/I/81OgdUV61UL._AC_SL1500_.jpg",
      imdb_score: "8.7",
      user_score: "",
      user_review: "",
      watch: false,
      to_watch: false,
    },
    {
      title: "Dune",
      genre: "Sci-Fi",
      synopsis: `A noble family becomes embroiled in a war for control over the galaxy's most valuable asset while its heir becomes troubled by visions of a dark future.`,
      release_date: "2021",
      rating: "PG-13",
      runtime: "2h 35m",
      director: "Dennis Villeneuve",
      poster_url:
        "https://m.media-amazon.com/images/I/51gOxvAKwfL._AC_SL1024_.jpg",
      imdb_score: "8.0",
      user_score: "",
      user_review: "",
      watch: false,
      to_watch: false,
    },
    {
      title: "The Conjuring",
      genre: "Horror",
      synopsis: `Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.`,
      release_date: "2013",
      rating: "R",
      runtime: "1h 52m",
      director: "James Wan",
      poster_url:
        "https://m.media-amazon.com/images/I/81YTU-rOk3L._AC_SL1500_.jpg",
      imdb_score: "7.5",
      user_score: "",
      user_review: "",
      watch: false,
      to_watch: false,
    },
    {
      title: "Spirited Away",
      genre: "Animation",
      synopsis: `During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches and spirits, a world where humans are changed into beasts.`,
      release_date: "2001",
      rating: "PG",
      runtime: "2h 5m",
      director: "Hayao Miyazaki",
      poster_url:
        "https://m.media-amazon.com/images/I/61ON14PVzoL._AC_SL1000_.jpg",
      imdb_score: "8.6",
      user_score: "",
      user_review: "",
      watch: false,
      to_watch: false,
    },
    {
      title: "Black Belt Jones",
      genre: "Action",
      synopsis: `A Mafia buy out of Papa Byrd's karate school downtown ends in his death. Byrd's daughter, Sydney, refuses to sell, and wants revenge. Byrd's students call the Black Belt Jones for help. Jones reluctantly teams with Sydney in many battles.`,
      release_date: "1974",
      rating: "R",
      runtime: "1h 25m",
      director: "Robert Clouse",
      poster_url: "https://m.media-amazon.com/images/I/51CDeI5MYJL._AC_.jpg",
      imdb_score: "6.2",
      user_score: "",
      user_review: "",
      watch: false,
      to_watch: false,
    },
    {
      title: "Tenacious D in The Pick of Destiny",
      genre: "Comedy",
      synopsis: `To become the greatest band of all time, two slacker, wannabe-rockers set out on a quest to steal a legendary guitar pick that gives its holders incredible guitar skills, from a maximum security Rock and Roll museum.`,
      release_date: "2006",
      rating: "R",
      runtime: "1h 34m",
      director: "Liam Lynch",
      poster_url: "https://m.media-amazon.com/images/I/510wmUa+GvL._AC_.jpg",
      imdb_score: "6.8",
      user_score: "",
      user_review: "",
      watch: false,
      to_watch: false,
    },
    {
      title: "Jay and Silent Bob Strike Back",
      genre: "Comedy",
      synopsis: `The comic "Bluntman and Chronic" is based on real-life stoners Jay and Silent Bob, so when they get no profit from a big-screen adaptation, they set out to wreck the movie.`,
      release_date: "2001",
      rating: "R",
      runtime: "1h 44m",
      director: "Kevin Smith",
      poster_url:
        "https://m.media-amazon.com/images/I/71y+LlpbTpL._AC_SL1500_.jpg",
      imdb_score: "6.8",
      user_score: "",
      user_review: "",
      watch: false,
      to_watch: false,
    },
    {
      title: "Finding Nemo",
      genre: "Animation",
      synopsis: `After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.`,
      release_date: "2003",
      rating: "G",
      runtime: "1h 40m",
      director: "Andrew Stanton & Lee Unkrich",
      poster_url:
        "https://m.media-amazon.com/images/I/71xJaSwRInL._AC_SL1500_.jpg",
      imdb_score: "8.2",
      user_score: "",
      user_review: "",
      watch: false,
      to_watch: false,
    },
  ]);
};
